version: 0.0
os: linux
files:
  - source: /
    destination: /C/Users/Gauri Valvi/Downloads/ci-cd-codedeploy-project/app
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
