name: Deploy to AWS using CodeDeploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Zip the app
        run: zip -r myapp.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: your-cicd-artifacts-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
          SOURCE_DIR: .
          DEST_DIR: /

      - name: Trigger CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: MyApp
          deployment-group: MyDeploymentGroup
          deployment-config-name: CodeDeployDefault.AllAtOnce
          s3-bucket: your-cicd-artifacts-bucket
          s3-key: myapp.zip
          bundle-type: zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
