name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zip project
        run: zip -r deployment.zip .

      - name: Upload to S3
        run: aws s3 cp deployment.zip s3://mybuck01234098/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name myapp \
            --deployment-group-name MyDG \
            --s3-location bucket=your-bucket-name,key=deployment.zip,bundleType=zip \
            --region eu-north-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
