name: Deploy to AWS using CodeDeploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: MyApp         # <-- Replace with your app name
          deployment-group: MyApp-BlueGreenGroup       # <-- Replace with your group name
          deployient-config: CodeDeployDefault.AllAtOnce
          region: ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

